package de.azaig.web.war.customer.model;

public enum ProfileProblem {
	MISSING_SESSION, MISSING_AUTHENTICATION, UNABLE_TO_FIND_USER, UNBORN_NOT_ALLOWED, AGE_IMPROBABLE, FIRSTNAME_TOO_SMALL, LASTNAME_TOO_SMALL, SECURITY_CHECK_FAILED, NOT_CHANGED_ANYTHING
}
