package de.azaig.web.war.customer.model;

public enum RegisrationProblem {
	NICK_ALREADY_IN_USE, PASSWORD_MISMATCH, PASSWORT_TOO_SHORT, INVALID_BIRTHDAY, MISSING_FIRSTNAME, MISSING_LASTNAME, AGB_MUST_CHECK, NICK_TOO_SHORT
}
