package de.azaig.web.war.offer.stuff.model;

public enum CreateOfferStuffProblem {
	PLEASE_CHOOSE_CATEGORY1, PLEASE_CHOOSE_CATEGORY2, PLEASE_CHOOSE_CATEGORY3, ADD_PICTURES, ADD_TEXT, TEXT_TOO_SMALL, TEXT_TOO_LONG, SET_BUSINESS_OR_NOT,
	PLEASE_LOGIN, PLEASE_ACCEPT_COOKIES, PLEASE_CHECK_AND_CONFIRM, PUBLISHED, DROPED
}
